require("user.plugins.auto-pairs")
require("user.plugins.lualine")
require("user.plugins.treesitter")
require("user.plugins.telescope")
require("user.plugins.toggleterm")
require("user.plugins.fidget")
require("user.plugins.gitsigns")
require("user.plugins.nvim-cmp")
require("user.plugins.web-devicons")
require("user.plugins.bufferline")
-- require("user.plugins.colorizer")
require("user.plugins.wilder")
